# Prettier default configuration (sorted by Schema order)
arrowParens: "always"
bracketSameLine: false
bracketSpacing: true
cursorOffset: -1
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
experimentalOperatorPosition: "end"
experimentalTernaries: false
# filepath: null
htmlWhitespaceSensitivity: "css"
insertPragma: false
jsxSingleQuote: false
objectWrap: "preserve"
# parser: null
plugins: []
printWidth: 80
proseWrap: "preserve"
quoteProps: "as-needed"
rangeEnd: null
rangeStart: 0
requirePragma: false
semi: true
singleAttributePerLine: false
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false
vueIndentScriptAndStyle: false
