packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@serialport/bindings-cpp'
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
  - vue-demi
