packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@serialport/bindings-cpp': true
  bcrypt: true
  esbuild: true
  msw: true
  sharp: true
  vue-demi: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@serialport/bindings-cpp'
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
  - vue-demi
