import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Vercel.App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const dark = cookie.get("mode");

  return (
    <html lang="en" className={dark?.value}>
      <body>{children}</body>
    </html>
  );
}
